[package]
name = "aravis-sys"
version = "0.0.1"
links = "aravis"
build = "build.rs"
[package.metadata.docs.rs]
features = ["dox"]

[lib]
name = "aravis_sys"

[dependencies]
gio-sys = "0.9.0"
glib-sys = "0.9.0"
gobject-sys = "0.9.0"
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.7"

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"

[features]
dox = []
