[package]
name = "aravis-sys"
version = "0.2.0"
description = "raw FFI-bindings for Aravis"
authors = ["RoboHouse <robohouse@robovalley.com>", "Maarten de Vries <maarten@de-vri.es>"]
license = "BSD-2-Clause"
keywords = ["GenICam", "GigE", "USB3", "Vision", "Camera"]
categories = ["multimedia::video"]
repository = "https://github.com/robohouse-delft/aravis-rs"
documentation = "https://docs.rs/aravis-sys"
links = "aravis"
build = "build.rs"
[package.metadata.docs.rs]
features = ["dox"]

[lib]
name = "aravis_sys"

[dependencies]
gio-sys = "0.9.0"
glib-sys = "0.9.0"
gobject-sys = "0.9.0"
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.7"

[dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"

[features]
dox = []
