[package]
name = "aravis-sys"
version = "0.7.0"
description = "raw FFI-bindings for Aravis"
authors = ["RoboHouse <robohouse@robovalley.com>", "Maarten de Vries <maarten@de-vri.es>"]
license = "BSD-2-Clause"
keywords = ["GenICam", "GigE", "USB3", "Vision", "Camera"]
categories = ["multimedia::video"]
repository = "https://github.com/robohouse-delft/aravis-rs"
documentation = "https://docs.rs/aravis-sys"
edition = "2018"
links = "aravis"
build = "build.rs"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.aravis]
name = "aravis-0.8"
version = "0.8"

[package.metadata.system-deps.aravis.v0_8_3]
name = "aravis-0.8"
version = "0.8.3"

[package.metadata.system-deps.aravis.v0_8_6]
version = "0.8.6"

[package.metadata.system-deps.aravis.v0_8_8]
version = "0.8.8"

[package.metadata.system-deps.aravis.v0_8_11]
version = "0.8.11"

[lib]
name = "aravis_sys"

[dependencies]
gio-sys = "0.14.0"
glib-sys = "0.14.0"
gobject-sys = "0.14.0"
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.7"
system-deps = "3"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
dox = []
v0_8_3 = []
v0_8_6 = ["v0_8_3"]
v0_8_8 = ["v0_8_6"]
v0_8_11 = ["v0_8_8"]
