[package]
name = "aravis"
version = "0.0.1"

[dependencies]
gio = "0.7.0"
gio-sys = "0.9.0"
glib = "0.8.2"
glib-sys = "0.9.0"
gobject-sys = "0.9.0"
aravis-sys = { version = "0.0.1", path = "../aravis-sys" }
