[package]
name = "aravis"
version = "0.2.0"
description = "safe bindings for Aravis, a vision library for genicam based cameras"
authors = [
	"RoboHouse <robohouse@robovalley.com>",
	"Maarten de Vries <maarten@de-vri.es>",
]
license = "BSD-2-Clause"
keywords = ["GenICam", "GigE", "USB3", "Vision", "Camera"]
categories = ["multimedia::video"]
repository = "https://github.com/robohouse-delft/aravis-rs"
documentation = "https://docs.rs/aravis"

[features]
default = ["bayer"]
dox = ["aravis-sys/dox"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
gio = "0.8.1"
gio-sys = "0.9.0"
glib = "0.9.3"
glib-sys = "0.9.0"
gobject-sys = "0.9.0"
aravis-sys = { version = "0.2.0", path = "../aravis-sys" }
image = "0.23.0"
bayer = { version = "0.1.5", optional = true }
