[package]
name = "aravis"
version = "0.8.1"
description = "safe bindings for Aravis, a vision library for genicam based cameras"
authors = [
	"RoboHouse <robohouse@robovalley.com>",
	"Maarten de Vries <maarten@de-vri.es>",
]
license = "BSD-2-Clause"
keywords = ["GenICam", "GigE", "USB3", "Vision", "Camera"]
categories = ["multimedia::video"]
repository = "https://github.com/robohouse-delft/aravis-rs"
documentation = "https://docs.rs/aravis"

[features]
dox = ["aravis-sys/dox", "nightly"]
nightly = []

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
aravis-sys = { version = "0.8.0", path = "../aravis-sys" }
bayer = { version = "0.1.5", optional = true }
gio = "0.15.10"
gio-sys = "0.15.10"
glib = "0.15.10"
glib-sys = "0.15.10"
gobject-sys = "0.15.10"
image = "0.24.1"

[build-dependencies]
rustc_version = "0.4.0"
