[package]
name = "aravis-utils"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[features]
default = ["gui"]
gui     = ["gtk", "gtk-sys", "gdk-pixbuf"]

[dependencies]
aravis     = {version = "0.0.2", path = "../aravis" }
env_logger = "0.7.1"
gio        = "0.7.0"
glib       = "0.8.0"
log        = "0.4.8"
png        = "0.15.0"
structopt  = "0.3.3"
gtk        = { version = "0.7.0", optional = true }
gtk-sys    = { version = "0.9.0", optional = true }
gdk-pixbuf = { version = "0.7.0", optional = true }
