[package]
name = "aravis-utils"
version = "0.6.0"
description = "command line utilities for interacting with GenICam cameras"
authors = ["RoboHouse <robohouse@robovalley.com>", "Maarten de Vries <maarten@de-vri.es>"]
license = "BSD-2-Clause"
keywords = ["GenICam", "GigE", "USB3", "Vision", "Camera"]
categories = ["multimedia::video"]
repository = "https://github.com/robohouse-delft/aravis-rs"

edition = "2018"

[features]
default = ["gui", "bayer"]
gui     = ["show-image"]
bayer   = ["aravis/bayer"]

[dependencies]
aravis     = { version="0.6.0", path="../aravis", features = ["bayer"] }
chrono     = "0.4.10"
env_logger = "0.8.1"
glib       = "0.10.0"
image      = "0.23.0"
log        = "0.4.8"
png        = "0.16.2"
show-image = { version="0.9.0", optional=true, features=["image", "save"] }
structopt  = "0.3.3"
