[package]
name = "aravis-utils"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[features]
default = ["gui"]
gui     = ["show-image"]

[dependencies]
aravis     = {version="0.0.2", path="../aravis" }
env_logger = "0.7.1"
gio        = "0.7.0"
glib       = "0.8.0"
image      = "0.23.0"
log        = "0.4.8"
png        = "0.15.0"
structopt  = "0.3.3"
show-image = { version="0.5.0", optional=true, features=["image", "save"] }
